using System.Text;

namespace CodeIndex.Database;

/// <summary>
/// Stable NFKC + Unicode CaseFold key for `--exact` symbol/reference name matching (#96).
/// SQLite's built-in NOCASE collation only folds ASCII, so common symbol-name pairs
/// like `Ä` / `ä`, fullwidth `Ｒｕｎ` / `Run`, Greek final sigma (`Σ` / `ς` / `σ`),
/// and sharp-S (`Straße` / `STRASSE`) would silently miss each other. This fold
/// normalizes to FormKC first, then applies full Unicode case folding.
///
/// Locale caveat: true Unicode CaseFold is still locale-invariant. Turkish dotted-I
/// therefore remains distinct from plain `i` (`İ` folds to `i\u0307`, not `i`), which
/// is the standard Unicode behavior. Matching that pair would require locale-sensitive
/// search semantics and would break the cross-platform stability contract of persisted
/// fold keys.
///
/// Stability contract: the same input MUST always fold to the same output across
/// OS / process boundaries, because the writer populates the column at index time
/// and the reader folds the query at lookup time — any drift would produce silent
/// misses. FormKC is stable per Unicode version, and the casefold delta table below
/// vendors only the code points where Unicode CaseFold differs from
/// `string.ToLowerInvariant()` after FormKC normalization.
///
/// `--exact` シンボル名マッチ用の NFKC + Unicode CaseFold key (#96)。SQLite の
/// NOCASE は ASCII 限定のため `Ä`/`ä`、全角/半角 `Ｒｕｎ`/`Run`、ギリシャ語 final
/// sigma (`Σ`/`ς`/`σ`)、sharp-S (`Straße`/`STRASSE`) を取りこぼす。この fold は
/// FormKC 正規化の上に true Unicode CaseFold を適用する。
///
/// ロケール注意: Unicode CaseFold は locale-invariant なので、トルコ語の `İ` は
/// 依然 `i` と同一視されず `i\u0307` に fold される。これは Unicode の正規挙動で、
/// ここで locale-sensitive な特例を入れると永続 fold key のクロスプラットフォーム
/// 安定性を壊す。
///
/// 安定性: writer と reader が同じ関数で同じ入力に同じ出力を返す必要があるため、
/// FormKC の後に .NET invariant lowercase と Unicode CaseFold の差分だけを vendoring
/// した決定的変換を使う。
/// </summary>
public static class NameFold
{
    /// <summary>
    /// Algorithm version for the persisted `name_folded` / `*_folded` keys. Bumped whenever
    /// <see cref="Fold"/> changes semantics so an upgraded reader can detect that a previously
    /// stamped DB's folded keys were generated by a different fold function and fall back to
    /// the `COLLATE NOCASE` path until a rebuild regenerates the keys. Without this, a
    /// Unicode CaseFold table refresh (or any future fold tweak) would silently mismatch
    /// against legacy keys and return wrong zero results on `--exact` queries.
    /// fold アルゴリズムのバージョン。Fold の意味が変わるたびに bump し、旧 key 版の DB を
    /// NOCASE fallback に降格させる（fold table 更新などに備えるメタデータ）。
    /// </summary>
    public const int Version = 2;


    /// <summary>
    /// Fold a symbol name for `--exact` equality comparison. Returns null for
    /// null input so legacy / missing values stay distinguishable.
    /// </summary>
    public static string? Fold(string? name)
    {
        if (name is null) return null;
        var normalized = name.Normalize(NormalizationForm.FormKC);
        var builder = new StringBuilder(normalized.Length + 8);
        foreach (var rune in normalized.EnumerateRunes())
        {
            if (!TryAppendCaseFoldDelta(builder, rune))
            {
                builder.Append(rune.ToString().ToLowerInvariant());
            }
        }

        return builder.ToString();
    }

    private static bool TryAppendCaseFoldDelta(StringBuilder builder, Rune rune)
    {
        // Cherokee is the biggest divergence from invariant-lower: Unicode casefold keeps
        // Cherokee in the uppercase block, while invariant lower maps many letters into the
        // Cherokee small-letter block. Handle those ranges arithmetically instead of carrying
        // 172 one-off table rows.
        // Cherokee は invariant lowercase と Unicode CaseFold の差分が大きいので range で畳む。
        var value = rune.Value;
        if (value is >= 0x13A0 and <= 0x13F5)
        {
            builder.Append(rune.ToString());
            return true;
        }

        if (value is >= 0x13F8 and <= 0x13FD)
        {
            AppendScalar(builder, value - 0x8);
            return true;
        }

        if (value is >= 0xAB70 and <= 0xABBF)
        {
            AppendScalar(builder, value - 0x97D0);
            return true;
        }

        // Greek prosgegrammeni / ypogegrammeni forms casefold by lowering the base letter
        // and expanding the subscript iota into a spacing iota.
        // Greek の prosgegrammeni / ypogegrammeni は base を lower した上で iota を展開する。
        if (value is >= 0x1F80 and <= 0x1F8F)
        {
            AppendScalar(builder, value - (value <= 0x1F87 ? 0x80 : 0x88));
            builder.Append('\u03B9');
            return true;
        }

        if (value is >= 0x1F90 and <= 0x1F9F)
        {
            AppendScalar(builder, value - (value <= 0x1F97 ? 0x70 : 0x78));
            builder.Append('\u03B9');
            return true;
        }

        if (value is >= 0x1FA0 and <= 0x1FAF)
        {
            AppendScalar(builder, value - (value <= 0x1FA7 ? 0x40 : 0x48));
            builder.Append('\u03B9');
            return true;
        }

        // Vendored delta table: only code points where NFKC + invariant-lower differs from
        // NFKC + Unicode CaseFold. This keeps the runtime logic small while still matching
        // the Unicode casefold algorithm exactly for persisted keys.
        // 差分テーブル: NFKC + ToLowerInvariant と Unicode CaseFold がズレる code point のみ。
        switch (value)
        {
            case 0x00DF: builder.Append("ss"); return true; // LATIN SMALL LETTER SHARP S
            case 0x0130: builder.Append("i\u0307"); return true; // LATIN CAPITAL LETTER I WITH DOT ABOVE
            case 0x01F0: builder.Append("j\u030C"); return true; // LATIN SMALL LETTER J WITH CARON
            case 0x0345: builder.Append("\u03B9"); return true; // COMBINING GREEK YPOGEGRAMMENI
            case 0x037A: builder.Append(" \u03B9"); return true; // GREEK YPOGEGRAMMENI
            case 0x0390: builder.Append("\u03B9\u0308\u0301"); return true; // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
            case 0x03B0: builder.Append("\u03C5\u0308\u0301"); return true; // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
            case 0x03C2: builder.Append("\u03C3"); return true; // GREEK SMALL LETTER FINAL SIGMA
            case 0x03F2: builder.Append("\u03C3"); return true; // GREEK LUNATE SIGMA SYMBOL
            case 0x1C80: builder.Append("\u0432"); return true; // CYRILLIC SMALL LETTER ROUNDED VE
            case 0x1C81: builder.Append("\u0434"); return true; // CYRILLIC SMALL LETTER LONG-LEGGED DE
            case 0x1C82: builder.Append("\u043E"); return true; // CYRILLIC SMALL LETTER NARROW O
            case 0x1C83: builder.Append("\u0441"); return true; // CYRILLIC SMALL LETTER WIDE ES
            case 0x1C84: builder.Append("\u0442"); return true; // CYRILLIC SMALL LETTER TALL TE
            case 0x1C85: builder.Append("\u0442"); return true; // CYRILLIC SMALL LETTER THREE-LEGGED TE
            case 0x1C86: builder.Append("\u044A"); return true; // CYRILLIC SMALL LETTER TALL HARD SIGN
            case 0x1C87: builder.Append("\u0463"); return true; // CYRILLIC SMALL LETTER TALL YAT
            case 0x1C88: builder.Append("\uA64B"); return true; // CYRILLIC SMALL LETTER UNBLENDED UK
            case 0x1E96: builder.Append("h\u0331"); return true; // LATIN SMALL LETTER H WITH LINE BELOW
            case 0x1E97: builder.Append("t\u0308"); return true; // LATIN SMALL LETTER T WITH DIAERESIS
            case 0x1E98: builder.Append("w\u030A"); return true; // LATIN SMALL LETTER W WITH RING ABOVE
            case 0x1E99: builder.Append("y\u030A"); return true; // LATIN SMALL LETTER Y WITH RING ABOVE
            case 0x1E9E: builder.Append("ss"); return true; // LATIN CAPITAL LETTER SHARP S
            case 0x1F50: builder.Append("\u03C5\u0313"); return true; // GREEK SMALL LETTER UPSILON WITH PSILI
            case 0x1F52: builder.Append("\u03C5\u0313\u0300"); return true; // GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
            case 0x1F54: builder.Append("\u03C5\u0313\u0301"); return true; // GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
            case 0x1F56: builder.Append("\u03C5\u0313\u0342"); return true; // GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
            case 0x1FB2: builder.Append("\u1F70\u03B9"); return true; // GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
            case 0x1FB3: builder.Append("\u03B1\u03B9"); return true; // GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
            case 0x1FB4: builder.Append("\u03AC\u03B9"); return true; // GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
            case 0x1FB6: builder.Append("\u03B1\u0342"); return true; // GREEK SMALL LETTER ALPHA WITH PERISPOMENI
            case 0x1FB7: builder.Append("\u03B1\u0342\u03B9"); return true; // GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
            case 0x1FBC: builder.Append("\u03B1\u03B9"); return true; // GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
            case 0x1FC2: builder.Append("\u1F74\u03B9"); return true; // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
            case 0x1FC3: builder.Append("\u03B7\u03B9"); return true; // GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
            case 0x1FC4: builder.Append("\u03AE\u03B9"); return true; // GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
            case 0x1FC6: builder.Append("\u03B7\u0342"); return true; // GREEK SMALL LETTER ETA WITH PERISPOMENI
            case 0x1FC7: builder.Append("\u03B7\u0342\u03B9"); return true; // GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
            case 0x1FCC: builder.Append("\u03B7\u03B9"); return true; // GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
            case 0x1FD2: builder.Append("\u03B9\u0308\u0300"); return true; // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
            case 0x1FD3: builder.Append("\u03B9\u0308\u0301"); return true; // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
            case 0x1FD6: builder.Append("\u03B9\u0342"); return true; // GREEK SMALL LETTER IOTA WITH PERISPOMENI
            case 0x1FD7: builder.Append("\u03B9\u0308\u0342"); return true; // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
            case 0x1FE2: builder.Append("\u03C5\u0308\u0300"); return true; // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
            case 0x1FE3: builder.Append("\u03C5\u0308\u0301"); return true; // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
            case 0x1FE4: builder.Append("\u03C1\u0313"); return true; // GREEK SMALL LETTER RHO WITH PSILI
            case 0x1FE6: builder.Append("\u03C5\u0342"); return true; // GREEK SMALL LETTER UPSILON WITH PERISPOMENI
            case 0x1FE7: builder.Append("\u03C5\u0308\u0342"); return true; // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
            case 0x1FF2: builder.Append("\u1F7C\u03B9"); return true; // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
            case 0x1FF3: builder.Append("\u03C9\u03B9"); return true; // GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
            case 0x1FF4: builder.Append("\u03CE\u03B9"); return true; // GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
            case 0x1FF6: builder.Append("\u03C9\u0342"); return true; // GREEK SMALL LETTER OMEGA WITH PERISPOMENI
            case 0x1FF7: builder.Append("\u03C9\u0342\u03B9"); return true; // GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
            case 0x1FFC: builder.Append("\u03C9\u03B9"); return true; // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
            case 0x1D6D3: builder.Append("\u03C3"); return true; // MATHEMATICAL BOLD SMALL FINAL SIGMA
            case 0x1D70D: builder.Append("\u03C3"); return true; // MATHEMATICAL ITALIC SMALL FINAL SIGMA
            case 0x1D747: builder.Append("\u03C3"); return true; // MATHEMATICAL BOLD ITALIC SMALL FINAL SIGMA
            case 0x1D781: builder.Append("\u03C3"); return true; // MATHEMATICAL SANS-SERIF BOLD SMALL FINAL SIGMA
            case 0x1D7BB: builder.Append("\u03C3"); return true; // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL FINAL SIGMA
            default: return false;
        }
    }

    private static void AppendScalar(StringBuilder builder, int scalarValue)
    {
        builder.Append(char.ConvertFromUtf32(scalarValue));
    }
}
