using System.Security.Cryptography;
using System.Text;

namespace CodeIndex.Database;

/// <summary>
/// Stable NFKC + invariant-lower fold for `--exact` symbol/reference name matching (#86).
/// SQLite's built-in NOCASE collation only folds ASCII, so common symbol-name pairs
/// like `Ä` / `ä` and fullwidth `Ｒｕｎ` / `Run` would silently miss each other. This
/// fold closes the common cases: Latin-1 accents, fullwidth/halfwidth, ligatures
/// (`ﬁ` → `fi`), superscripts, compatibility Kana.
///
/// NOT full Unicode CaseFold. `string.ToLowerInvariant()` is close but not identical
/// to the Unicode casefolding algorithm, so a few edge-case pairs still diverge —
/// the classic example is Turkish dotted-I: `"İ".Normalize(FormKC).ToLowerInvariant()`
/// can return `"i\u0307"` (i + combining dot above) on some runtimes instead of `"i"`,
/// so `İ`-vs-`i` does not match through this fold. Greek final sigma (`Σ`/`ς`/`σ`)
/// and some combining-mark normalization corners can also slip. Callers who need
/// guaranteed Unicode-correct case folding should pass the exact casing found during
/// indexing. See #96 for the follow-up on a true CaseFold key.
///
/// Stability contract: the same input MUST always fold to the same output across
/// OS / process boundaries, because the writer populates the column at index time
/// and the reader folds the query at lookup time — any drift would produce silent
/// misses. FormKC is stable per Unicode version; `ToLowerInvariant` uses the
/// .NET-embedded invariant tables.
///
/// `--exact` シンボル名マッチ用の NFKC + invariant-lower 折り畳み (#86)。SQLite の
/// NOCASE は ASCII 限定のため `Ä`/`ä` や全角/半角 `Ｒｕｎ`/`Run` を取りこぼす。この
/// fold は Latin-1 アクセント、全角/半角、合字、互換 Kana 等の現実的な casing を
/// カバーする。ただし完全な Unicode CaseFold ではない: トルコ語の `İ`/`i`、ギリシャ
/// 語 final sigma (`Σ`/`ς`/`σ`) などのエッジケースは拾えない（詳細は #96）。
/// 安定性: writer と reader が同じ関数で同じ入力に同じ出力を返す必要があるため、
/// OS / プロセスに依存しない決定的変換である FormKC + ToLowerInvariant を使う。
/// </summary>
public static class NameFold
{
    private static readonly string[] FingerprintCanaries =
    [
        "Ä",
        "İ",
        "ﬁ",
        "Ｒｕｎ",
        "\u00DF",
        "Σ",
        "ς",
    ];

    /// <summary>
    /// Algorithm version for the persisted `name_folded` / `*_folded` keys. Bumped whenever
    /// <see cref="Fold"/> changes semantics so an upgraded reader can detect that a previously
    /// stamped DB's folded keys were generated by a different fold function and fall back to
    /// the `COLLATE NOCASE` path until a rebuild regenerates the keys. Without this, #96's
    /// switch to a true Unicode CaseFold (or any future fold tweak) would silently mismatch
    /// against legacy keys and return wrong zero results on `--exact` queries.
    /// fold アルゴリズムのバージョン。Fold の意味が変わるたびに bump し、旧 key 版の DB を
    /// NOCASE fallback に降格させる（#96 の完全 CaseFold 等に備えるメタデータ）。
    /// </summary>
    public const int Version = 1;

    /// <summary>
    /// Runtime-sensitive canary fingerprint for the current observable fold output.
    /// Folded keys are trusted only when both <see cref="Version"/> and this fingerprint
    /// match the runtime that produced them. This catches invariant casing / ICU drift
    /// across .NET upgrades even when the logical fold algorithm version stays constant.
    /// runtime 依存の fold 出力差分を拾う canary fingerprint。Version に加えてこれも一致
    /// したときだけ folded key を trusted とみなす（.NET / ICU drift 対策）。
    /// </summary>
    public static string Fingerprint()
    {
        var buffer = new StringBuilder();
        foreach (var canary in FingerprintCanaries)
        {
            buffer.Append(Fold(canary));
            buffer.Append('|');
        }

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(buffer.ToString()));
        return Convert.ToHexString(hash[..8]);
    }


    /// <summary>
    /// Fold a symbol name for `--exact` equality comparison. Returns null for
    /// null input so legacy / missing values stay distinguishable.
    /// </summary>
    public static string? Fold(string? name)
    {
        if (name is null) return null;
        // FormKC: compatibility decomposition + canonical recomposition.
        // Collapses fullwidth / halfwidth, ligatures (ﬁ → fi), superscripts,
        // compatibility Kana, and precomposed / decomposed accents to a single
        // canonical form. Then ToLowerInvariant folds most ASCII + Latin-1 case
        // (Ä → ä) without locale surprises. Does NOT implement full Unicode
        // CaseFold — see the class doc for the edge cases (Turkish İ, Greek
        // final sigma) that still need exact casing. #96 tracks the full fix.
        // FormKC + ToLowerInvariant で現実的な casing を畳む。完全 CaseFold は #96。
        return name.Normalize(NormalizationForm.FormKC).ToLowerInvariant();
    }
}
